export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('legends').del()

  // Inserts seed entries
  await knex('legends').insert([
    {
      name: 'Andre The Giant',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Batista',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Big Boss Man',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Boogeyman',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Booker T',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Bray Wyatt',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Bret Hart',
      fightingStyle: 'Technician',
      faction: 'The Hart Foundation',
      dlc: false,
    },
    {
      name: 'British Bulldog',
      fightingStyle: 'Powerhouse',
      faction: 'The Hart Foundation',
      dlc: false,
    },
    {
      name: 'Bruno Sammartino',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Cactus Jack',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    // {
    //   name: 'Diamond Dallas Page',
    //   fightingStyle: '',
    //   faction: null,
    //   dlc: true,
    // },
    {
      name: 'Diesel',
      fightingStyle: 'Powerhouse',
      faction: 'Two Dudes with Attitudes',
      dlc: false,
    },
    {
      name: 'Doink The Clown',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Dude Love',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Eddie Guerrero',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Eric Bischoff',
      fightingStyle: 'Striker',
      faction: 'New World Order',
      dlc: false,
    },
    {
      name: 'Faarooq',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'George "The Animal" Steele',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Harley Race',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Headbanger Mosh',
      fightingStyle: 'Striker',
      faction: 'The Headbangers',
      dlc: true,
    },
    {
      name: 'Headbanger Thrasher',
      fightingStyle: 'Striker',
      faction: 'The Headbangers',
      dlc: true,
    },
    {
      name: 'Hollywood Hogan',
      fightingStyle: 'Powerhouse',
      faction: 'New World Order',
      dlc: false,
    },
    {
      name: 'Honky Tonk Man',
      fightingStyle: 'Technician',
      faction: null,
      dlc: true,
    },
    {
      name: 'Hulk Hogan',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Jake "The Snake" Roberts',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'JBL',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Jerry "The King" Lawler',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Jim "The Anvil" Neidhart',
      fightingStyle: 'Powerhouse',
      faction: 'The Hart Foundation',
      dlc: false,
    },
    {
      name: 'Kane',
      fightingStyle: 'Powerhouse',
      faction: 'The Brothers of Destruction',
      dlc: false,
    },
    {
      name: 'Kane 08',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Ken Shamrock',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Kevin Nash',
      fightingStyle: 'Powerhouse',
      faction: 'New World Order',
      dlc: false,
    },
    {
      name: 'Kurt Angle',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    // {
    //   name: 'Lex Luger',
    //   fightingStyle: '',
    //   faction: '',
    //   dlc: '',
    // },
    {
      name: '"Macho Man" Randy Savage',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
    },
    {
      name: 'Mankind',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    // {
    //   name: 'Mr Perfect',
    //   fightingStyle: '',
    //   faction: '',
    //   dlc: '',
    // },
    {
      name: 'Muhammad Ali',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: '"Ravishing" Rick Rude',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Razor Ramon',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Rick Steiner',
      fightingStyle: 'Technician',
      faction: 'The Steiner Brothers',
      dlc: false,
    },
    {
      name: 'Ricky "The Dragon" Steamboat',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
    },
    {
      name: 'Rikishi',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Rob Van Dam',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
    },
    {
      name: '"Rowdy" Roddy Piper',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Sandman',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: true,
    },
    {
      name: 'Scott Hall',
      fightingStyle: 'Powerhouse',
      faction: 'New World Order',
      dlc: false,
    },
    {
      name: 'Scott Steiner',
      fightingStyle: 'Technician',
      faction: 'The Steiner Brothers',
      dlc: '',
    },
    {
      name: 'Shane McMahon',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Shawn Michaels',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: '"Stone Cold" Steve Austin',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Syxx',
      fightingStyle: 'Striker',
      faction: 'New World Order',
      dlc: false,
    },
    {
      name: 'Ted DiBiase',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Terry Funk',
      fightingStyle: 'Technician',
      faction: null,
      dlc: true,
    },
    {
      name: 'The Fiend Bray Wyatt',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    // {
    //   name: 'The Great Muta',
    //   fightingStyle: '',
    //   faction: '',
    //   dlc: '',
    // },
    {
      name: 'The Hurricane',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    // {
    //   name: 'The Iron Sheik',
    //   fightingStyle: '',
    //   faction: '',
    //   dlc: '',
    // },
    {
      name: 'The Rock',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Triple H',
      fightingStyle: 'Powerhouse',
      faction: 'The Authority',
      dlc: false,
    },
    {
      name: 'Triple H 08',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Ultimate Warrior',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Umaga',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Undertaker',
      fightingStyle: 'Striker',
      faction: 'The Brothers of Destruction',
      dlc: false,
    },
    {
      name: 'Vader',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Wade Barrett',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'William Regal',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'X-Pac',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Yokozuna',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
  ])
}
