export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('legends_mens').del()

  // Inserts seed entries
  await knex('legends_mens').insert([
    {
      name: 'Andre The Giant',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Batista',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Big Boss Man',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Boogeyman',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Booker T',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Bray Wyatt',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Bret Hart',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'The Hart Foundation',
      dlc: false,
    },
    {
      name: 'British Bulldog',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'The Hart Foundation',
      dlc: false,
    },
    {
      name: 'Bruno Sammartino',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Bubba Ray Dudley',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Cactus Jack',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Diesel',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'Two Dudes with Attitudes',
      dlc: false,
    },
    {
      name: 'Doink The Clown',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Dude Love',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Dusty Rhodes',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: true,
    },
    {
      name: 'Eddie Guerrero',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Eric Bischoff',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'New World Order',
      dlc: false,
    },
    {
      name: 'Faarooq',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'George "The Animal" Steele',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Harley Race',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Headbanger Mosh',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'The Headbangers',
      dlc: true,
    },
    {
      name: 'Headbanger Thrasher',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'The Headbangers',
      dlc: true,
    },
    {
      name: 'Hollywood Hogan',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'New World Order',
      dlc: false,
    },
    {
      name: 'Honky Tonk Man',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: true,
    },
    {
      name: 'Hulk Hogan',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Jake "The Snake" Roberts',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'JBL',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Jerry "The King" Lawler',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Jim "The Anvil" Neidhart',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The Hart Foundation',
      dlc: false,
    },
    {
      name: 'Kane',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The Brothers of Destruction',
      dlc: false,
    },
    {
      name: 'Kane 08',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Ken Shamrock',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Kevin Nash',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'New World Order',
      dlc: false,
    },
    {
      name: 'Kurt Angle',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: '"Macho Man" Randy Savage',
      alignment: 'Heel',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
    },
    {
      name: 'Mankind',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Muhammad Ali',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: '"Ravishing" Rick Rude',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Razor Ramon',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Rick Steiner',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'The Steiner Brothers',
      dlc: false,
    },
    {
      name: 'Ricky "The Dragon" Steamboat',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
    },
    {
      name: 'Rikishi',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Rob Van Dam',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
    },
    {
      name: '"Rowdy" Roddy Piper',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Sandman',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: true,
    },
    {
      name: 'Scott Hall',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'New World Order',
      dlc: false,
    },
    {
      name: 'Scott Steiner',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'The Steiner Brothers',
      dlc: false,
    },
    {
      name: 'Shane McMahon',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Shawn Michaels',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: '"Stone Cold" Steve Austin',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Syxx',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'New World Order',
      dlc: false,
    },
    {
      name: 'Ted DiBiase',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Terry Funk',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: true,
    },
    {
      name: 'The Fiend Bray Wyatt',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'The Hurricane',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'The Rock',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Triple H',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'The Authority',
      dlc: false,
    },
    {
      name: 'Triple H 08',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Ultimate Warrior',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Umaga',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Undertaker',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'The Brothers of Destruction',
      dlc: false,
    },
    {
      name: 'Vader',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Wade Barrett',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'William Regal',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'X-Pac',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Yokozuna',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
  ])
}
