export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('legends').del()

  // Inserts seed entries
  await knex('legends').insert([
    { name: 'Andre The Giant' },
    { name: 'Batista' },
    { name: 'Big Boss Man' },
    { name: 'Boogeyman' },
    { name: 'Booker T' },
    { name: 'Bray Wyatt' },
    { name: 'Bret Hart' },
    { name: 'British Bulldog' },
    { name: 'Bruno Sammartino' },
    { name: 'Cactus Jack' },
    { name: 'Diamond Dallas Page' },
    { name: 'Diesel' },
    { name: 'Doink The Clown' },
    { name: 'Dude Love' },
    { name: 'Eddie Guerrero' },
    { name: 'Eric Bischoff' },
    { name: 'Faarooq' },
    { name: 'George "The Animal" Steele' },
    { name: 'Harley Race' },
    { name: 'Headbanger Mosh' },
    { name: 'Headbanger Thrasher' },
    { name: 'Hollywood Hogan' },
    { name: 'Honky Tonk Man' },
    { name: 'Hulk Hogan' },
    { name: 'Jake "The Snake" Roberts' },
    { name: 'JBL' },
    { name: 'Jerry "The King" Lawler' },
    { name: 'Jim "The Anvil" Neidhart' },
    { name: 'Kane' },
    { name: 'Kane 08' },
    { name: 'Ken Shamrock' },
    { name: 'Kevin Nash' },
    { name: 'Kurt Angle' },
    { name: 'Lex Luger' },
    { name: 'Macho Man Randy Savage' },
    { name: 'Mankind' },
    { name: 'Mr Perfect' },
    { name: 'Muhammad Ali' },
    { name: 'Ravishing Rick Rude' },
    { name: 'Razor Ramon' },
    { name: 'Rick Steiner' },
    { name: 'Ricky Steamboat' },
    { name: 'Rikishi' },
    { name: 'Rob Van Dam' },
    { name: 'Rowdy Roddy Piper' },
    { name: 'Sandman' },
    { name: 'Scott Hall' },
    { name: 'Scott Steiner' },
    { name: 'Shane McMahon' },
    { name: 'Shawn Michaels' },
    { name: 'Stone Cold Steve Austin' },
    { name: 'Syxx' },
    { name: 'Ted DiBiase' },
    { name: 'Terry Funk' },
    { name: 'The Fiend Bray Wyatt' },
    { name: 'The Great Muta' },
    { name: 'The Hurricane' },
    { name: 'The Iron Sheik' },
    { name: 'The Rock' },
    { name: 'Triple H' },
    { name: 'Triple H 08' },
    { name: 'Ultimate Warrior' },
    { name: 'Umaga' },
    { name: 'Undertaker' },
    { name: 'Vader' },
    { name: 'Wade Barrett' },
    { name: 'William Regal' },
    { name: 'X-Pac' },
    { name: 'Yokozuna' },
  ])
}
