export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('superstar-womens').del()

  // Inserts seed entries
  await knex('superstar-womens').insert([
    { name: 'Alba Fyre' },
    { name: 'Alexa Bliss' },
    { name: 'Asuka' },
    { name: 'Bayley' },
    { name: 'Becky Lynch' },
    { name: 'Bianca Belair' },
    { name: 'Blair Davenport' },
    { name: 'Candice LeRae' },
    { name: 'Carmella' },
    { name: 'Charlotte Flair' },
    { name: 'Chelsea Green' },
    { name: 'Cora Jade' },
    { name: 'Dakota Kai' },
    { name: 'Fallon Henley' },
    { name: 'Gigi Dolin' },
    { name: 'Indi Hartwell' },
    { name: 'Isla Dawn' },
    { name: 'Ivy Nile' },
    { name: 'Iyo Sky' },
    { name: 'Jacy Jayne' },
    { name: 'Jade Cargill' },
    { name: 'Kairi Sane' },
    { name: 'Katana Chance' },
    { name: 'Kayden Carter' },
    { name: 'Liv Morgan' },
    { name: 'Lyra Valkyria' },
    { name: 'Maryse' },
    { name: 'Maxxine Dupri' },
    { name: 'Michin' },
    { name: 'Natalya' },
    { name: 'Nia Jax' },
    { name: 'Nikki Cross' },
    { name: 'Nikkita Lyons' },
    { name: 'Piper Niven' },
    { name: 'Raquel Rodriguez' },
    { name: 'Rhea Ripley' },
    { name: 'Ronda Rousey' },
    { name: 'Roxanne Perez' },
    { name: 'Scarlett' },
    { name: 'Shayna Baszler' },
    { name: 'Shotzi' },
    { name: 'Sonya Deville' },
    { name: 'Tamina' },
    { name: 'Tegan Nox' },
    { name: 'Thea Hail' },
    { name: 'Tiffany Stratton' },
    { name: 'Valhalla' },
    { name: 'Wendy Choo' },
    { name: 'Xia Li' },
    { name: 'Zelina Vega' },
    { name: 'Zoey Stark' },
  ])
}
