export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('superstar-womens').del()

  // Inserts seed entries
  await knex('superstar-womens').insert([
    {
      name: 'Alba Fyre',
      fightingStyle: 'Striker',
      faction: 'Alba Fyre & Isla Dawn',
      dlc: false,
    },
    {
      name: 'Alexa Bliss',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Asuka',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Bayley',
      fightingStyle: 'Technician',
      faction: 'Damage CTRL',
      dlc: false,
    },
    {
      name: 'Becky Lynch',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Bianca Belair',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Blair Davenport',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Candice LeRae',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Carmella',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Charlotte Flair',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Chelsea Green',
      fightingStyle: 'Striker',
      faction: 'Piper Niven & Chelsea Green',
      dlc: false,
    },
    {
      name: 'Cora Jade',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Dakota Kai',
      fightingStyle: 'Striker',
      faction: 'Damage CTRL',
      dlc: false,
    },
    {
      name: 'Fallon Henley',
      fightingStyle: 'Striker',
      faction: 'Briggs & Jensen',
      dlc: false,
    },
    {
      name: 'Gigi Dolin',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Indi Hartwell',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Isla Dawn',
      fightingStyle: 'Striker',
      faction: 'Alba Fyre & Isla Dawn',
      dlc: false,
    },
    {
      name: 'Ivy Nile',
      fightingStyle: 'Powerhouse',
      faction: 'The Creed Brothers',
      dlc: false,
    },
    {
      name: 'Iyo Sky',
      fightingStyle: 'High Flyer',
      faction: 'Damage CTRL',
      dlc: false,
    },
    {
      name: 'Jacy Jayne',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    // {
    //   name: 'Jade Cargill',
    //   fightingStyle: 'Powerhouse',
    //   faction: '',
    //   dlc: true,
    // },
    // {
    //   name: 'Kairi Sane',
    //   fightingStyle: '',
    //   faction: 'Damage CTRL',
    //   dlc: true,
    // },
    {
      name: 'Katana Chance',
      fightingStyle: 'High Flyer',
      faction: 'Katana Chance & Kayden Carter',
      dlc: false,
    },
    {
      name: 'Kayden Carter',
      fightingStyle: 'Technician',
      faction: 'Katana Chance & Kayden Carter',
      dlc: false,
    },
    {
      name: 'Liv Morgan',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    // {
    //   name: 'Lyra Valkyria',
    //   fightingStyle: '',
    //   faction: null,
    //   dlc: true,
    // },
    {
      name: 'Maryse',
      fightingStyle: 'Striker',
      faction: 'The Miz & Maryse',
      dlc: false,
    },
    {
      name: 'Maxxine Dupri',
      fightingStyle: 'Striker',
      faction: 'Alpha Academy',
      dlc: false,
    },
    {
      name: 'Michin',
      fightingStyle: 'Striker',
      faction: 'The O.C.',
      dlc: false,
    },
    {
      name: 'Natalya',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    // {
    //   name: 'Nia Jax',
    //   fightingStyle: 'Powerhouse',
    //   faction: null,
    //   dlc: true,
    // },
    {
      name: 'Nikki Cross',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Nikkita Lyons',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Piper Niven',
      fightingStyle: 'Powerhouse',
      faction: 'Piper Niven & Chelsea Green',
      dlc: false,
    },
    {
      name: 'Raquel Rodriguez',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Rhea Ripley',
      fightingStyle: 'Powerhouse',
      faction: 'The Judgment Day',
      dlc: false,
    },
    {
      name: 'Roxanne Perez',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Scarlett',
      fightingStyle: 'Striker',
      faction: 'Karrion Kross & Scarlett',
      dlc: '',
    },
    {
      name: 'Shayna Baszler',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Shotzi',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Sonya Deville',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Tamina',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Tegan Nox',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Thea Hail',
      fightingStyle: 'Striker',
      faction: 'Chase U',
      dlc: false,
    },
    {
      name: 'Tiffany Stratton',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Valhalla',
      fightingStyle: 'Striker',
      faction: 'The Viking Raiders',
      dlc: false,
    },
    {
      name: 'Wendy Choo',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Xia Li',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Zelina Vega',
      fightingStyle: 'High Flyer',
      faction: 'Latino World Order',
      dlc: false,
    },
    {
      name: 'Zoey Stark',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
  ])
}
