export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('superstar-womens').del()

  // Inserts seed entries
  await knex('superstar-womens').insert([
    {
      name: 'Alba Fyre',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'Alba Fyre & Isla Dawn',
      dlc: false,
    },
    {
      name: 'Alexa Bliss',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Asuka',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Bayley',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'Damage CTRL',
      dlc: false,
    },
    {
      name: 'Becky Lynch',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Bianca Belair',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Blair Davenport',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Candice LeRae',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Carmella',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Charlotte Flair',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Chelsea Green',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'Piper Niven & Chelsea Green',
      dlc: false,
    },
    {
      name: 'Cora Jade',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Dakota Kai',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'Damage CTRL',
      dlc: false,
    },
    {
      name: 'Fallon Henley',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'Briggs & Jensen',
      dlc: false,
    },
    {
      name: 'Gigi Dolin',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Indi Hartwell',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Isla Dawn',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'Alba Fyre & Isla Dawn',
      dlc: false,
    },
    {
      name: 'Ivy Nile',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The Creed Brothers',
      dlc: false,
    },
    {
      name: 'Iyo Sky',
      alignment: 'Heel',
      fightingStyle: 'High Flyer',
      faction: 'Damage CTRL',
      dlc: false,
    },
    {
      name: 'Jacy Jayne',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Katana Chance',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: 'Katana Chance & Kayden Carter',
      dlc: false,
    },
    {
      name: 'Kayden Carter',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'Katana Chance & Kayden Carter',
      dlc: false,
    },
    {
      name: 'Liv Morgan',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Maryse',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Miz & Maryse',
      dlc: false,
    },
    {
      name: 'Maxxine Dupri',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'Alpha Academy',
      dlc: false,
    },
    {
      name: 'Michin',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'The O.C.',
      dlc: false,
    },
    {
      name: 'Natalya',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Nikki Cross',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Nikkita Lyons',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Piper Niven',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'Piper Niven & Chelsea Green',
      dlc: false,
    },
    {
      name: 'Raquel Rodriguez',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Rhea Ripley',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'The Judgment Day',
      dlc: false,
    },
    {
      name: 'Roxanne Perez',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Scarlett',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'Karrion Kross & Scarlett',
      dlc: false,
    },
    {
      name: 'Shayna Baszler',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Shotzi',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Sonya Deville',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Tamina',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Tegan Nox',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Thea Hail',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'Chase U',
      dlc: false,
    },
    {
      name: 'Tiffany Stratton',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Valhalla',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Viking Raiders',
      dlc: false,
    },
    {
      name: 'Wendy Choo',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Xia Li',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Zelina Vega',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: 'Latino World Order',
      dlc: false,
    },
    {
      name: 'Zoey Stark',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
  ])
}
