export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('superstar-mens').del()

  // Inserts seed entries
  await knex('superstar-mens').insert([
    { name: 'AJ Hawk' },
    { name: 'AJ Styles' },
    { name: 'Akira Tozawa' },
    { name: 'Andre Chase' },
    { name: 'Angel Garza' },
    { name: 'Angelo Dawkins' },
    { name: 'Apollo Crews' },
    { name: 'Ashante Thee Adonis' },
    { name: 'Austin Theory' },
    { name: 'Axiom' },
    { name: 'Bad Bunny' },
    { name: 'Baron Corbin' },
    { name: 'Big E' },
    { name: 'Bobby Lashley' },
    { name: 'Boston Connor' },
    { name: 'Braun Strowman' },
    { name: 'Bray Wyatt' },
    { name: 'Bron Breakker' },
    { name: 'Bronson Reed' },
    { name: 'Brooks Jensen' },
    { name: 'Brutus Creed' },
    { name: 'Butch' },
    { name: 'Cameron Grimes' },
    { name: 'Carlito' },
    { name: 'Carmelo Hayes' },
    { name: 'Cedric Alexander' },
    { name: 'Chad Gable' },
    { name: 'Channing "Stacks" Lorenzo' },
    { name: 'CM Punk' },
    { name: 'Cody Rhodes' },
    { name: 'Cruz Del Toro' },
    { name: 'Damien Priest' },
    { name: 'Damon Kemp' },
    { name: 'Darius Butler' },
    { name: 'Dexter Lumis' },
    { name: 'Dijak' },
    { name: '"Dirty" Dominik Mysterio' },
    { name: 'Dragon Lee' },
    { name: 'Drew Gulak' },
    { name: 'Drew McIntyre' },
    { name: 'Duke Hudson' },
    { name: 'Elton Prince' },
    { name: 'Erik' },
    { name: 'Finn Balor' },
    { name: 'Giovanni Vinci' },
    { name: 'Grayson Waller' },
    { name: 'Gunther' },
    { name: 'Humberto Carrillo' },
    { name: 'Ilja Dragunov' },
    { name: 'Ivar' },
    { name: 'JD McDonagh' },
    { name: 'Jey Uso' },
    { name: 'Jimmy Uso' },
    { name: 'Jinder Mahal' },
    { name: 'Joaquin Wilde' },
    { name: 'Joe Coffey' },
    { name: 'Joe Gacy' },
    { name: 'John Cena' },
    { name: 'Johnny Gargano' },
    { name: 'Josh Briggs' },
    { name: 'Julius Creed' },
    { name: 'Karl Anderson' },
    { name: 'Karrion Kross' },
    { name: 'Kevin Owens' },
    { name: 'Kit Wilson' },
    { name: 'Kofi Kingston' },
    { name: 'LA Knight' },
    { name: 'Logan Paul' },
    { name: 'Ludwig Kaiser' },
    { name: 'Luke Gallows' },
    { name: 'Mark Coffey' },
    { name: 'Montez Ford' },
    { name: 'MVP' },
    { name: 'Nathan Frazer' },
    { name: 'Noam Dar' },
    { name: 'Omos' },
    { name: 'Otis' },
    { name: 'Pat McAfee' },
    { name: 'Post Malone' },
    { name: 'R-Truth' },
    { name: 'Randy Orton' },
    { name: 'Rey Mysterio' },
    { name: 'Ricochet' },
    { name: 'Ridge Holland' },
    { name: 'Robert Roode' },
    { name: 'Roman Reigns' },
    { name: 'Sami Zayn' },
    { name: 'Sanga' },
    { name: 'Santos Escobar' },
    { name: 'Scrypts' },
    { name: 'Seth Rollins' },
    { name: 'Sheamus' },
    { name: 'Shinsuke Nakamura' },
    { name: 'Solo Sikoa' },
    { name: 'The Miz' },
    { name: 'Tommaso Ciampa' },
    { name: 'Tony DAngelo' },
    { name: 'Trick Williams' },
    { name: 'Ty Schmit' },
    { name: 'Tyler Bate' },
    { name: 'Tyler Breeze' },
    { name: 'Veer Mahaan' },
    { name: 'Wes Lee' },
    { name: 'Wolfgang' },
    { name: 'Xavier Woods' },
  ])
}
