export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('superstar_mens').del()

  // Inserts seed entries
  await knex('superstar_mens').insert([
    {
      name: 'AJ Hawk',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: true,
    },
    {
      name: 'AJ Styles',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'The O.C.',
      dlc: false,
    },
    {
      name: 'Akira Tozawa',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'Alpha Academy',
      dlc: false,
    },
    {
      name: 'Andre Chase',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'Chase U',
      dlc: false,
    },
    {
      name: 'Angel Garza',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'Los Lotharios',
      dlc: false,
    },
    {
      name: 'Angelo Dawkins',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The Street Profits',
      dlc: false,
    },
    {
      name: 'Apollo Crews',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Ashante Thee Adonis',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Austin Theory',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Axiom',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
    },
    {
      name: 'Bad Bunny',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Baron Corbin',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Big E',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The New Day',
      dlc: false,
    },
    {
      name: 'Bobby Lashley',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Boston Connor',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: 'The Toxic Table',
      dlc: true,
    },
    {
      name: 'Braun Strowman',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Bray Wyatt',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Bron Breakker',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Bronson Reed',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Brooks Jensen',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'Briggs & Jensen',
      dlc: false,
    },
    {
      name: 'Brutus Creed',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The Creed Brothers',
      dlc: false,
    },
    {
      name: 'Butch',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'The Brawling Brutes',
      dlc: false,
    },
    {
      name: 'Cameron Grimes',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Carmelo Hayes',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
    },
    {
      name: 'Cedric Alexander',
      alignment: 'Heel',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
    },
    {
      name: 'Chad Gable',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'Alpha Academy',
      dlc: false,
    },
    {
      name: 'Channing "Stacks" Lorenzo',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'DAngelo & Lorenzo',
      dlc: false,
    },
    {
      name: 'CM Punk',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: true,
    },
    {
      name: 'Cody Rhodes',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Cruz Del Toro',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: 'Latino World Order',
      dlc: false,
    },
    {
      name: 'Damien Priest',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Judgment Day',
      dlc: false,
    },
    {
      name: 'Damon Kemp',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Darius Butler',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
    },
    {
      name: 'Dexter Lumis',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Dijak',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: '"Dirty" Dominik Mysterio',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Judgment Day',
      dlc: false,
    },
    {
      name: 'Drew Gulak',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Drew McIntyre',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Duke Hudson',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'Chase U',
      dlc: false,
    },
    {
      name: 'Elton Prince',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'Pretty Deadly',
      dlc: false,
    },
    {
      name: 'Erik',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Viking Raiders',
      dlc: false,
    },
    {
      name: 'Finn Balor',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Judgment Day',
      dlc: false,
    },
    {
      name: 'Giovanni Vinci',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'Imperium',
      dlc: false,
    },
    {
      name: 'Grayson Waller',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Gunther',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'Imperium',
      dlc: false,
    },
    {
      name: 'Humberto Carrillo',
      alignment: 'Heel',
      fightingStyle: 'High Flyer',
      faction: 'Los Lotharios',
      dlc: false,
    },
    {
      name: 'Ilja Dragunov',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Ivar',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'The Viking Raiders',
      dlc: false,
    },
    {
      name: 'JD McDonagh',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'The Judgment Day',
      dlc: false,
    },
    {
      name: 'Jey Uso',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Jimmy Uso',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Bloodline',
      dlc: false,
    },
    {
      name: 'Jinder Mahal',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'Indus Sher',
      dlc: false,
    },
    {
      name: 'Joaquin Wilde',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: 'Latino World Order',
      dlc: false,
    },
    {
      name: 'Joe Coffey',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'Gallus',
      dlc: false,
    },
    {
      name: 'Joe Gacy',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'John Cena',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Johnny Gargano',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: '#DIY',
      dlc: false,
    },
    {
      name: 'Josh Briggs',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'Briggs & Jensen',
      dlc: false,
    },
    {
      name: 'Julius Creed',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The Creed Brothers',
      dlc: false,
    },
    {
      name: 'Karl Anderson',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'The O.C.',
      dlc: false,
    },
    {
      name: 'Karrion Kross',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'Karrion Kross & Scarlett',
      dlc: false,
    },
    {
      name: 'Kevin Owens',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'Kevin Owens & Sami Zayn',
      dlc: false,
    },
    {
      name: 'Kit Wilson',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'Pretty Deadly',
      dlc: false,
    },
    {
      name: 'Kofi Kingston',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'The New Day',
      dlc: false,
    },
    {
      name: 'LA Knight',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Logan Paul',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Ludwig Kaiser',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'Imperium',
      dlc: false,
    },
    {
      name: 'Luke Gallows',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The O.C.',
      dlc: false,
    },
    {
      name: 'Mark Coffey',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'Gallus',
      dlc: false,
    },
    {
      name: 'Montez Ford',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: 'The Street Profits',
      dlc: false,
    },
    {
      name: 'MVP',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Nathan Frazer',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
    },
    {
      name: 'Noam Dar',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Omos',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
    },
    {
      name: 'Otis',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'Alpha Academy',
      dlc: false,
    },
    {
      name: 'Pat McAfee',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: true,
    },
    {
      name: 'Post Malone',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: true,
    },
    {
      name: 'R-Truth',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Randy Orton',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Rey Mysterio',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: 'Latino World Order',
      dlc: false,
    },
    {
      name: 'Ricochet',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
    },
    {
      name: 'Ridge Holland',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The Brawling Brutes',
      dlc: false,
    },
    {
      name: 'Robert Roode',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Roman Reigns',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'The Bloodline',
      dlc: false,
    },
    {
      name: 'Sami Zayn',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'Kevin Owens & Sami Zayn',
      dlc: false,
    },
    {
      name: 'Sanga',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'Indus Sher',
      dlc: false,
    },
    {
      name: 'Santos Escobar',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'Latino World Order',
      dlc: false,
    },
    {
      name: 'Scrypts',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
    },
    {
      name: 'Seth Rollins',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Sheamus',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'The Brawling Brutes',
      dlc: false,
    },
    {
      name: 'Shinsuke Nakamura',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Solo Sikoa',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Bloodline',
      dlc: false,
    },
    {
      name: 'The Miz',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Miz & Maryse',
      dlc: false,
    },
    {
      name: 'Tommaso Ciampa',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: '#DIY',
      dlc: false,
    },
    {
      name: 'Tony DAngelo',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'DAngelo & Lorenzo',
      dlc: false,
    },
    {
      name: 'Trick Williams',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
    },
    {
      name: 'Ty Schmit',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'The Toxic Table',
      dlc: true,
    },
    {
      name: 'Tyler Bate',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
    },
    {
      name: 'Veer Mahaan',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'Indus Sher',
      dlc: false,
    },
    {
      name: 'Wes Lee',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
    },
    {
      name: 'Wolfgang',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'Gallus',
      dlc: false,
    },
    {
      name: 'Xavier Woods',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'The New Day',
      dlc: false,
    },
  ])
}
