/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('wrestlers').del()
  await knex('wrestlers').insert([
    {
      name: 'AJ Hawk',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: true,
      isLegend: false,
    },
    {
      name: 'AJ Styles',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'The O.C.',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Akira Tozawa',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'Alpha Academy',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Alba Fyre',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'Alba Fyre & Isla Dawn',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Alexa Bliss',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Andre Chase',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'Chase U',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Andre The Giant',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Angel Garza',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'Los Lotharios',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Angelo Dawkins',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The Street Profits',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Apollo Crews',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Ashante Thee Adonis',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Asuka',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Austin Theory',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Axiom',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Bad Bunny',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Baron Corbin',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Batista',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Bayley',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'Damage CTRL',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Becky Lynch',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Beth Phoenix',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Bianca Belair',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Big Boss Man',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Big E',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The New Day',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Blair Davenport',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Bobby Lashley',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Boogeyman',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Booker T',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Boston Connor',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: 'The Toxic Table',
      dlc: true,
      isLegend: false,
    },
    {
      name: 'Braun Strowman',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Bray Wyatt',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Bret Hart',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'The Hart Foundation',
      dlc: false,
      isLegend: true,
    },
    {
      name: 'British Bulldog',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'The Hart Foundation',
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Bron Breakker',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Bronson Reed',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Brooks Jensen',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'Briggs & Jensen',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Bruno Sammartino',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Brutus Creed',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The Creed Brothers',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Bubba Ray Dudley',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Butch',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'The Brawling Brutes',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Cactus Jack',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Cameron Grimes',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Candice LeRae',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Carmella',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Carmelo Hayes',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Cedric Alexander',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Chad Gable',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'Alpha Academy',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Channing "Stacks" Lorenzo',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'DAngelo & Lorenzo',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Charlotte Flair',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Chelsea Green',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'Piper Niven & Chelsea Green',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Chyna',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'CM Punk',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: true,
      isLegend: false,
    },
    {
      name: 'Cody Rhodes',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Cora Jade',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Cruz Del Toro',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: 'Latino World Order',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'D-Von Dudley',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The Dudley Boyz',
      dlc: true,
      isLegend: true,
    },
    {
      name: 'Dakota Kai',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'Damage CTRL',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Damien Priest',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Judgment Day',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Damon Kemp',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Darius Butler',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: true,
      isLegend: false,
    },
    {
      name: 'Dexter Lumis',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Diesel',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'Two Dudes with Attitudes',
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Dijak',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: '"Dirty" Dominik Mysterio',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Judgment Day',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Doink The Clown',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Drew Gulak',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Drew McIntyre',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Dude Love',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Duke Hudson',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'Chase U',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Dusty Rhodes',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: true,
      isLegend: true,
    },
    {
      name: 'Eddie Guerrero',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Elton Prince',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'Pretty Deadly',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Eric Bischoff',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'New World Order',
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Erik',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Viking Raiders',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Eve Torres',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Faarooq',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Fallon Henley',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'Briggs & Jensen',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'The Fiend Bray Wyatt',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Finn Balor',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Judgment Day',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'George "The Animal" Steele',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Gigi Dolin',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Giovanni Vinci',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'Imperium',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Grayson Waller',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Gunther',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'Imperium',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Harley Race',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Hollywood Hogan',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'New World Order',
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Honky Tonk Man',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: true,
      isLegend: true,
    },
    {
      name: 'Hulk Hogan',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Humberto Carrillo',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'High Flyer',
      faction: 'Los Lotharios',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'The Hurricane',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Ilja Dragunov',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Indi Hartwell',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Isla Dawn',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'Alba Fyre & Isla Dawn',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Ivar',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'The Viking Raiders',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Ivy Nile',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The Creed Brothers',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Iyo Sky',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'High Flyer',
      faction: 'Damage CTRL',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Jacy Jayne',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Jake "The Snake" Roberts',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'JBL',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'JD McDonagh',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'The Judgment Day',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Jerry "The King" Lawler',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Jey Uso',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Jim "The Anvil" Neidhart',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The Hart Foundation',
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Jimmy Uso',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Bloodline',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Jinder Mahal',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'Indus Sher',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Joaquin Wilde',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: 'Latino World Order',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Joe Coffey',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'Gallus',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Joe Gacy',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'John Cena',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Johnny Gargano',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: '#DIY',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Josh Briggs',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'Briggs & Jensen',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Julius Creed',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The Creed Brothers',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Kane',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The Brothers of Destruction',
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Kane 08',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Karl Anderson',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'The O.C.',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Karrion Kross',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'Karrion Kross & Scarlett',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Katana Chance',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: 'Katana Chance & Kayden Carter',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Kayden Carter',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'Katana Chance & Kayden Carter',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Ken Shamrock',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Kevin Nash',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'New World Order',
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Kevin Owens',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'Kevin Owens & Sami Zayn',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'King Booker',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Kit Wilson',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'Pretty Deadly',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Kofi Kingston',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'The New Day',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Kurt Angle',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'LA Knight',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Lita',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Liv Morgan',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Logan Paul',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Ludwig Kaiser',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'Imperium',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Luke Gallows',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The O.C.',
      dlc: false,
      isLegend: false,
    },
    {
      name: '"Macho Man" Randy Savage',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Mankind',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Mark Coffey',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'Gallus',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Maryse',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Miz & Maryse',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Maryse',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Miz & Maryse',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Maxxine Dupri',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'Alpha Academy',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Michin',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'The O.C.',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Mighty Molly',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'The Miz',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Miz & Maryse',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Molly Holly',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Montez Ford',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: 'The Street Profits',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Mosh',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'The Headbangers',
      dlc: true,
      isLegend: true,
    },
    {
      name: 'Muhammad Ali',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'MVP',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Natalya',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Nathan Frazer',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Nikki Cross',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Nikkita Lyons',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Noam Dar',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Omos',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Otis',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'Alpha Academy',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Pat McAfee',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: true,
      isLegend: false,
    },
    {
      name: 'Piper Niven',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'Piper Niven & Chelsea Green',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Post Malone',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: true,
      isLegend: false,
    },
    {
      name: 'R-Truth',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Randy Orton',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Raquel Rodriguez',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: '"Ravishing" Rick Rude',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Razor Ramon',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Rey Mysterio',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: 'Latino World Order',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Rey Mysterio Jr.',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Rhea Ripley',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'The Judgment Day',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Rick Steiner',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'The Steiner Brothers',
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Ricky "The Dragon" Steamboat',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Ricochet',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Ridge Holland',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: 'The Brawling Brutes',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Rikishi',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Rob Van Dam',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Robert Roode',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'The Rock',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'The Rock 01',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Roman Reigns',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'The Bloodline',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Roman Reigns 15',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Ronda Rousey',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: '"Rowdy" Roddy Piper',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Roxanne Perez',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Sami Zayn',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'Kevin Owens & Sami Zayn',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'The Sandman',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: true,
      isLegend: true,
    },
    {
      name: 'Sanga',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'Indus Sher',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Santos Escobar',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'Latino World Order',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Scarlett',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'Karrion Kross & Scarlett',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Scott Hall',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'New World Order',
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Scott Steiner',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'The Steiner Brothers',
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Scrypts',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Sensational Sherri',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: true,
      isLegend: true,
    },
    {
      name: 'Seth Rollins',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Seth Rollins 15',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: 'The Authority',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Shane McMahon',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Shawn Michaels',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Shayna Baszler',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Sheamus',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'The Brawling Brutes',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Shinsuke Nakamura',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Shotzi',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Solo Sikoa',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Bloodline',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Sonya Deville',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Stacy Keibler',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Stardust',
      gender: 'male',
      alignment: 'face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: true,
      isLegend: false,
    },
    {
      name: 'Stephanie McMahon',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Authority',
      dlc: false,
      isLegend: true,
    },
    {
      name: '"Stone Cold" Steve Austin',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: '"Superstar" Billy Graham',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: true,
      isLegend: true,
    },
    {
      name: 'Syxx',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'New World Order',
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Tamina',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Ted DiBiase',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Tegan Nox',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Terry Funk',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: true,
      isLegend: true,
    },
    {
      name: 'Thea Hail',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'Chase U',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Thrasher',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'The Headbangers',
      dlc: true,
      isLegend: true,
    },
    {
      name: 'Tiffany Stratton',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Tommaso Ciampa',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: '#DIY',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Tony DAngelo',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'DAngelo & Lorenzo',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Trick Williams',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Triple H',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'The Authority',
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Triple H 08',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Trish Stratus',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Ty Schmit',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: 'The Toxic Table',
      dlc: true,
      isLegend: false,
    },
    {
      name: 'Tyler Bate',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Tyler Breeze',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Ultimate Warrior',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Umaga',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Uncle Howdy',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: '"Undashing" Cody Rhodes',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: true,
      isLegend: false,
    },
    {
      name: 'Undertaker',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'The Brothers of Destruction',
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Vader',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Valhalla',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: 'The Viking Raiders',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Veer Mahaan',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'Indus Sher',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Wade Barrett',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Wendy Choo',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Wes Lee',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'William Regal',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Technician',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Wolfgang',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: 'Gallus',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'X-Pac',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Xavier Woods',
      gender: 'male',
      alignment: 'Face',
      fightingStyle: 'Striker',
      faction: 'The New Day',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Xia Li',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Yokozuna',
      gender: 'male',
      alignment: 'Heel',
      fightingStyle: 'Powerhouse',
      faction: null,
      dlc: false,
      isLegend: true,
    },
    {
      name: 'Zelina Vega',
      gender: 'female',
      alignment: 'Face',
      fightingStyle: 'High Flyer',
      faction: 'Latino World Order',
      dlc: false,
      isLegend: false,
    },
    {
      name: 'Zoey Stark',
      gender: 'female',
      alignment: 'Heel',
      fightingStyle: 'Striker',
      faction: null,
      dlc: false,
      isLegend: false,
    },
  ])
}
